USE [master]
GO

/****** Object:  Database [fotm]    Script Date: 2/2/2016 4:35:54 PM ******/
CREATE DATABASE [fotm]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'fotm', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\fotm.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'fotm_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\fotm_log.ldf' , SIZE = 6912KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [fotm] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [fotm].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [fotm] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [fotm] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [fotm] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [fotm] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [fotm] SET ARITHABORT OFF 
GO

ALTER DATABASE [fotm] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [fotm] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [fotm] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [fotm] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [fotm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [fotm] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [fotm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [fotm] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [fotm] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [fotm] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [fotm] SET  DISABLE_BROKER 
GO

ALTER DATABASE [fotm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [fotm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [fotm] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [fotm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [fotm] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [fotm] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [fotm] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [fotm] SET RECOVERY FULL 
GO

ALTER DATABASE [fotm] SET  MULTI_USER 
GO

ALTER DATABASE [fotm] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [fotm] SET DB_CHAINING OFF 
GO

ALTER DATABASE [fotm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [fotm] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [fotm] SET  READ_WRITE 
GO

