#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlavorOfTheMonth
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="fotm")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLeaderboard(Leaderboard instance);
    partial void UpdateLeaderboard(Leaderboard instance);
    partial void DeleteLeaderboard(Leaderboard instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["fotmConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Leaderboard> Leaderboards
		{
			get
			{
				return this.GetTable<Leaderboard>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Leaderboard")]
	public partial class Leaderboard : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _LeaderboardID;
		
		private string _Ranking;
		
		private string _Rating;
		
		private string _Name;
		
		private string _RealmID;
		
		private string _RealmName;
		
		private string _RealmSlug;
		
		private System.Nullable<int> _RaceID;
		
		private System.Nullable<int> _ClassID;
		
		private System.Nullable<int> _SpecID;
		
		private System.Nullable<int> _FactionID;
		
		private System.Nullable<int> _GenderID;
		
		private System.Nullable<int> _SeasonWins;
		
		private System.Nullable<int> _SeasonLosses;
		
		private System.Nullable<int> _WeeklyWins;
		
		private System.Nullable<int> _WeeklyLosses;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		private System.Nullable<char> _ModifiedStatus;
		
		private System.Nullable<long> _ModifiedUserID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLeaderboardIDChanging(long value);
    partial void OnLeaderboardIDChanged();
    partial void OnRankingChanging(string value);
    partial void OnRankingChanged();
    partial void OnRatingChanging(string value);
    partial void OnRatingChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnRealmIDChanging(string value);
    partial void OnRealmIDChanged();
    partial void OnRealmNameChanging(string value);
    partial void OnRealmNameChanged();
    partial void OnRealmSlugChanging(string value);
    partial void OnRealmSlugChanged();
    partial void OnRaceIDChanging(System.Nullable<int> value);
    partial void OnRaceIDChanged();
    partial void OnClassIDChanging(System.Nullable<int> value);
    partial void OnClassIDChanged();
    partial void OnSpecIDChanging(System.Nullable<int> value);
    partial void OnSpecIDChanged();
    partial void OnFactionIDChanging(System.Nullable<int> value);
    partial void OnFactionIDChanged();
    partial void OnGenderIDChanging(System.Nullable<int> value);
    partial void OnGenderIDChanged();
    partial void OnSeasonWinsChanging(System.Nullable<int> value);
    partial void OnSeasonWinsChanged();
    partial void OnSeasonLossesChanging(System.Nullable<int> value);
    partial void OnSeasonLossesChanged();
    partial void OnWeeklyWinsChanging(System.Nullable<int> value);
    partial void OnWeeklyWinsChanged();
    partial void OnWeeklyLossesChanging(System.Nullable<int> value);
    partial void OnWeeklyLossesChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    partial void OnModifiedStatusChanging(System.Nullable<char> value);
    partial void OnModifiedStatusChanged();
    partial void OnModifiedUserIDChanging(System.Nullable<long> value);
    partial void OnModifiedUserIDChanged();
    #endregion
		
		public Leaderboard()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaderboardID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long LeaderboardID
		{
			get
			{
				return this._LeaderboardID;
			}
			set
			{
				if ((this._LeaderboardID != value))
				{
					this.OnLeaderboardIDChanging(value);
					this.SendPropertyChanging();
					this._LeaderboardID = value;
					this.SendPropertyChanged("LeaderboardID");
					this.OnLeaderboardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ranking", DbType="NVarChar(50)")]
		public string Ranking
		{
			get
			{
				return this._Ranking;
			}
			set
			{
				if ((this._Ranking != value))
				{
					this.OnRankingChanging(value);
					this.SendPropertyChanging();
					this._Ranking = value;
					this.SendPropertyChanged("Ranking");
					this.OnRankingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="NVarChar(50)")]
		public string Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this.OnRatingChanging(value);
					this.SendPropertyChanging();
					this._Rating = value;
					this.SendPropertyChanged("Rating");
					this.OnRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealmID", DbType="NVarChar(50)")]
		public string RealmID
		{
			get
			{
				return this._RealmID;
			}
			set
			{
				if ((this._RealmID != value))
				{
					this.OnRealmIDChanging(value);
					this.SendPropertyChanging();
					this._RealmID = value;
					this.SendPropertyChanged("RealmID");
					this.OnRealmIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealmName", DbType="NVarChar(50)")]
		public string RealmName
		{
			get
			{
				return this._RealmName;
			}
			set
			{
				if ((this._RealmName != value))
				{
					this.OnRealmNameChanging(value);
					this.SendPropertyChanging();
					this._RealmName = value;
					this.SendPropertyChanged("RealmName");
					this.OnRealmNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealmSlug", DbType="NVarChar(50)")]
		public string RealmSlug
		{
			get
			{
				return this._RealmSlug;
			}
			set
			{
				if ((this._RealmSlug != value))
				{
					this.OnRealmSlugChanging(value);
					this.SendPropertyChanging();
					this._RealmSlug = value;
					this.SendPropertyChanged("RealmSlug");
					this.OnRealmSlugChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaceID", DbType="Int")]
		public System.Nullable<int> RaceID
		{
			get
			{
				return this._RaceID;
			}
			set
			{
				if ((this._RaceID != value))
				{
					this.OnRaceIDChanging(value);
					this.SendPropertyChanging();
					this._RaceID = value;
					this.SendPropertyChanged("RaceID");
					this.OnRaceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="Int")]
		public System.Nullable<int> ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecID", DbType="Int")]
		public System.Nullable<int> SpecID
		{
			get
			{
				return this._SpecID;
			}
			set
			{
				if ((this._SpecID != value))
				{
					this.OnSpecIDChanging(value);
					this.SendPropertyChanging();
					this._SpecID = value;
					this.SendPropertyChanged("SpecID");
					this.OnSpecIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactionID", DbType="Int")]
		public System.Nullable<int> FactionID
		{
			get
			{
				return this._FactionID;
			}
			set
			{
				if ((this._FactionID != value))
				{
					this.OnFactionIDChanging(value);
					this.SendPropertyChanging();
					this._FactionID = value;
					this.SendPropertyChanged("FactionID");
					this.OnFactionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderID", DbType="Int")]
		public System.Nullable<int> GenderID
		{
			get
			{
				return this._GenderID;
			}
			set
			{
				if ((this._GenderID != value))
				{
					this.OnGenderIDChanging(value);
					this.SendPropertyChanging();
					this._GenderID = value;
					this.SendPropertyChanged("GenderID");
					this.OnGenderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeasonWins", DbType="Int")]
		public System.Nullable<int> SeasonWins
		{
			get
			{
				return this._SeasonWins;
			}
			set
			{
				if ((this._SeasonWins != value))
				{
					this.OnSeasonWinsChanging(value);
					this.SendPropertyChanging();
					this._SeasonWins = value;
					this.SendPropertyChanged("SeasonWins");
					this.OnSeasonWinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeasonLosses", DbType="Int")]
		public System.Nullable<int> SeasonLosses
		{
			get
			{
				return this._SeasonLosses;
			}
			set
			{
				if ((this._SeasonLosses != value))
				{
					this.OnSeasonLossesChanging(value);
					this.SendPropertyChanging();
					this._SeasonLosses = value;
					this.SendPropertyChanged("SeasonLosses");
					this.OnSeasonLossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeeklyWins", DbType="Int")]
		public System.Nullable<int> WeeklyWins
		{
			get
			{
				return this._WeeklyWins;
			}
			set
			{
				if ((this._WeeklyWins != value))
				{
					this.OnWeeklyWinsChanging(value);
					this.SendPropertyChanging();
					this._WeeklyWins = value;
					this.SendPropertyChanged("WeeklyWins");
					this.OnWeeklyWinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeeklyLosses", DbType="Int")]
		public System.Nullable<int> WeeklyLosses
		{
			get
			{
				return this._WeeklyLosses;
			}
			set
			{
				if ((this._WeeklyLosses != value))
				{
					this.OnWeeklyLossesChanging(value);
					this.SendPropertyChanging();
					this._WeeklyLosses = value;
					this.SendPropertyChanged("WeeklyLosses");
					this.OnWeeklyLossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedStatus", DbType="Char(1)")]
		public System.Nullable<char> ModifiedStatus
		{
			get
			{
				return this._ModifiedStatus;
			}
			set
			{
				if ((this._ModifiedStatus != value))
				{
					this.OnModifiedStatusChanging(value);
					this.SendPropertyChanging();
					this._ModifiedStatus = value;
					this.SendPropertyChanged("ModifiedStatus");
					this.OnModifiedStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedUserID", DbType="BigInt")]
		public System.Nullable<long> ModifiedUserID
		{
			get
			{
				return this._ModifiedUserID;
			}
			set
			{
				if ((this._ModifiedUserID != value))
				{
					this.OnModifiedUserIDChanging(value);
					this.SendPropertyChanging();
					this._ModifiedUserID = value;
					this.SendPropertyChanged("ModifiedUserID");
					this.OnModifiedUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
